// Env interface is now auto-generated by `wrangler types`
// See worker-configuration.d.ts

import { handleV1 } from './v1/handler';
// import { handleV2 } from './v2/handler'; // Future

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    // CORS headers for all responses
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };

    // Handle preflight requests
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    try {
      // Route to version-specific handlers
      if (path.startsWith('/api/v1/')) {
        return handleV1(request, env.CHOOSER_DB_V1, corsHeaders);
      }

      // Future version
      // if (path.startsWith('/api/v2/')) {
      //   return handleV2(request, env.CHOOSER_DB_V2, corsHeaders);
      // }

      return new Response('Not found', { status: 404, headers: corsHeaders });
    } catch (error) {
      const error_message = error instanceof Error ? error.message : String(error);
      return new Response(`Error: ${error_message}`, {
        status: 500,
        headers: corsHeaders
      });
    }
  }
};
